### ISSUE TITLE
Relationships not working

### ISSUE THREAD

**Issue by emaxedon** [vinctustech/energize#6]
Before, if we had the following resource definitions:
```
resource books
	title string required unique
	description string optional
	authors authors array
	publisher publishers

resource authors
	name string required

resource publishers
	name string required
```

We could create publishers, and then create books with one-to-many relationships with publishers. The creation works, but when trying to retrieve books, the following error is produced:

```
Expected ',' instead of 'I'
```

Here's a snippet from the stack trace:
```
org.h2.jdbc.JdbcSQLException: Ambiguous column name "ID"; SQL statement:
energize[ERROR] SELECT title,description,null as authors,publisher,id FROM books LEFT OUTER JOIN publishers ON books.publisher = publishers.id 
```

**Comment by edadma** [comment]
Not reproducible using API definition

	resource books
		title string
		author authors
		publisher publishers
		
	resource authors
		name string unique

	resource publishers
		name string unique

	if size( books ) == 0
		batchInsert( publishers, [["North Point Press"], ["Enhanced Media"], ["Amazon Classics"]] )

		insert( authors, {name: "Fyodor Dostoyevsky"} )
		insert( authors, {name: "Lewis Carroll"} )
		insert( authors, {name: "Mark Twain"} )

		insert( books, {title: "The Brothers Karamazov", author: "Fyodor Dostoyevsky", publisher: "North Point Press"} )
		insert( books, {title: "Alice's Adventures in Wonderland", author: "Lewis Carroll", publisher: "Enhanced Media"} )
		insert( books, {title: "The Adventures of Huckleberry Finn", author: "Mark Twain", publisher: "Amazon Classics"} )

which is the `examples/books.energize` example that ships with the project. So, it's likely that the problem involves many-to-many relationships.

continuing to investigate...

**Comment by edadma** [comment]
Not reproducible using

	resource students
		name string unique
		classrooms classrooms array
	
	resource classrooms
		number string unique
	
	if size( students ) == 0
		batchInsert( students, [["rayna"], ["soren"], ["carys"], ["larkin"]] )
		batchInsert( classrooms, [["101"], ["105"], ["208"], ["302"], ["307"]] )
		associate( students, "name", "rayna", classrooms, "number", "105" )
		associate( students, "name", "rayna", classrooms, "number", "307" )
		associate( students, "name", "soren", classrooms, "number", "208" )
		associate( students, "name", "soren", classrooms, "number", "307" )

which is the `examples/students.energize` example that ships with the project. So, it's likely that the problem involves resources that have a mixture of one-to-many and many-to-many relationships.

continuing to investigate...

**Comment by emaxedon** [comment]
Let's say we have the following `energize` definition.

```
resource books
  title string
  authors authors array
  publisher publishers

resource authors
  name string unique

resource publishers
  name string unique
```

First, create a book.
```
POST http://localhost:8080/books HTTP/1.1
Content-Type: applicaton/json

{
  "title": "Dune: House Atreides"
}
```

Then, create the book's authors relationships.
```
POST http://localhost:8080/books/1/authors HTTP/1.1
Content-Type: application/json

{
  "name": "Brian Herbert"
}
```

And again for the other author...
```
POST http://localhost:8080/books/1/authors HTTP/1.1
Content-Type: application/json

{
  "name": "Kevin J. Anderson"
}
```

Finally, retrieve the book.
```
GET http://localhost:8080/books/1 HTTP/1.1
```

This should return an error `Expected ',' instead of 'I'`.

The server logs:
```
org.h2.jdbc.JdbcSQLException: Ambiguous column name "ID"; SQL statement:
SELECT title,null as author,publisher,id FROM books LEFT OUTER JOIN publishers ON books.publisher = publishers.id WHERE books.id = 1
```

**Comment by edadma** [comment]
https://github.com/vinctustech/energize/commit/0c1ff64f658594fbf6fbe5581d3bdbab526cbc33
