### ISSUE TITLE
Allow energize to parse .json formatted config

### ISSUE THREAD

**Issue by emaxedon** [vinctustech/energize#9]

**Comment by edadma** [comment]
basic JSON REST definition working

in SBT type `assembly` to get an executable jar in `target/scala-2.12` in the project folder

put the following simple definition in a file called `int.json` (in that folder)
``` json
{
  "tables": [
    {
      "name": "r",
      "resource": true,
      "fields": [
        {
          "name": "f",
          "type": {
            "category": "primitive",
            "type": "integer"
          }
        }
      ]
    }
  ]
}
```
The commands

    cat int.json|java -jar energize-0.8.jar -j --

and

    java -jar energize-0.8.jar -j int.json

are equivalent
